### ISSUE TITLE
create rpm for coreos-installer 

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#1]
Let's create an rpm so this software can be picked up and included in Fedora CoreOS.

**Comment by dustymabe** [comment]
Will try to knock this out tomorrow morning.

**Comment by dustymabe** [comment]
copr repo with coreos-installer rpm in it: https://copr.fedorainfracloud.org/coprs/dustymabe/coreos-installer/build/858699/

**Comment by yrobla** [comment]
Great! Going to try it

**Comment by dustymabe** [comment]
package review: https://bugzilla.redhat.com/show_bug.cgi?id=1677668

**Comment by dustymabe** [comment]
Package passed review (https://bugzilla.redhat.com/show_bug.cgi?id=1677668) and is making it's way into fedora. Going to close this. (https://bodhi.fedoraproject.org/updates/coreos-installer-0-1.git081d4be.fc29)
