### ISSUE TITLE
no network access without emergency shell hack

### ISSUE THREAD

**Issue by imcleod** [coreos/coreos-installer#10]
This relates to the following build of the installer content:

https://ci.centos.org/artifacts/fedora-coreos/prod/builds/29.746/

Using iPXE and the kernel and ramdisk from the builds above, I've been able to install both FCOS and a recent RHCOS test release onto actual physical HW (in my case, a Lenovo T500 laptop).  However, I have to manually force the network to come up before downloading the image and ignition files works.  More specifically, I have to add the following to the kernel command line:

rd.break=initqueue

Which gets to an emergency shell prior the installer attempting to run.  I can then "ifup enp0s25", exit the shell and all moves along perfectly.

I've also tried adding the following two options to the kernel command line without success:

ip=dhcp

and

ip=enp0s25:dhcp

Only the manual ifup in the shell works.

Note that both the booted FCOS and RHCOS systems _do_ bring up network successfully.

**Comment by mrguitar** [comment]
I thought Fedora was moving to NetworkManager in the initrd. I guess that's still not there by default. :/

**Comment by imcleod** [comment]
OK.  The solution is detailed a bit further down in the README.  You need to inform dracut of the need for network  Adding the following to the kernel CLI works:

ip=dhcp rd.neednet=1

With this in place I am able to provision completely non-interactively, including on packet.net.
