### ISSUE TITLE
RPM CI is broken because nmstate uses Rust 1.60 dependency syntax

### ISSUE THREAD

**Issue by bgilbert** [coreos/coreos-installer#1039]
Well, unfortunately #1032 wasn't the end of it.  We hand-tested [FEDORA-2022-b499698493](https://bodhi.fedoraproject.org/updates/FEDORA-2022-b499698493) by manually installing all the coreos-installer build dependencies in a container, and indeed the nmstate package is installable and produces a successful build.

However, automatic depsolving doesn't work, because rust2rpm [doesn't yet support](https://pagure.io/fedora-rust/rust2rpm/issue/186) the new 1.60 dependency syntax.  As a result, rust-coreos-installer [currently FTBFS](https://kojipkgs.fedoraproject.org//work/tasks/6222/93696222/build.log) in Fedora:

```
+ /usr/bin/env CARGO_HOME=.cargo RUSTC_BOOTSTRAP=1 'RUSTFLAGS=-Copt-level=3 -Cdebuginfo=2 -Ccodegen-units=1 -Clink-arg=-Wl,-z,relro -Clink-arg=-Wl,-z,now -Clink-arg=-Wl,-dT,/builddir/build/BUILD/coreos-installer-0.16.1/.package_note-rust-coreos-installer-0.16.1-2.fc36.x86_64.ld --cap-lints=warn' /usr/bin/cargo build -j6 -Z avoid-dev-deps --release --features rdcore
error: no matching package named `nispor` found
location searched: registry `crates-io`
required by package `nmstate v2.2.0`
    ... which satisfies dependency `nmstate = "^2.1.2"` of package `coreos-installer v0.16.1 (/builddir/build/BUILD/coreos-installer-0.16.1)`
error: Bad exit status from /var/tmp/rpm-tmp.6RIcM4 (%build)
```

@cathay4t, maybe `nmstate.spec` could manually add the subpackage dependencies that rust2rpm currently can't produce on its own?  Another option might be to avoid the new dependency syntax upstream for now.

**Comment by bgilbert** [comment]
For now, I'm going to mark the RPM test non-required so we can merge things in this repo.  The fix will need to happen in the nmstate packaging.

also cc @qinqon for visibility.

**Comment by cathay4t** [comment]
@bgilbert You mean add something like these to `rust-nmstate+default-devel` and `rust-nmstate+gen_conf-devel`?

```
BuildRequires:  (crate(nispor/default) >= 1.2.8 with crate(nispor/default) < 2.0)
```

**Comment by bgilbert** [comment]
It appears to me that it:
- should be `Requires` rather than `BuildRequires`,
- only needs to happen in `rust-nmstate+gen_conf-devel` (because `rust-nmstate+default-devel` requires `crate(nmstate/query_apply)`), and
- would need to happen for all of the `dep:` dependencies, so `nispor`, `nix`, `libc`, and `zbus`.

**Comment by cathay4t** [comment]
OK. Will do.

**Comment by bgilbert** [comment]
@cathay4t The nmstate package dependencies are still broken, causing RPM build failures for coreos-installer both in our upstream CI and in actual Fedora.  Could you take a look please?

Note that #1038 is unrelated.  Even if we bumped our MSRV and switched to only using `gen_conf`, Fedora tooling can't yet handle 1.60-style dependencies.

**Comment by cathay4t** [comment]
This  should be fixed by Fedora update nmstate-2.2.2-2.fc36 and nmstate-2.2.2-2.fc37. Could you try again?

**Comment by bgilbert** [comment]
[It wasn't](https://github.com/coreos/coreos-installer/actions/runs/3706878030/jobs/6538001681).  Could you point me to the change that should have fixed the problem?  I'm looking at the upstream `Cargo.toml` and the downstream specfile, and not finding anything that looks like a fix.

**Comment by cathay4t** [comment]
Aha, I missed the +gen_conf-devel part. Let me do it now.

**Comment by cathay4t** [comment]
I have released nmstate 2.2.3 in fedora(currently in testing repo). With 2.2.3, I have removed the need of `dep:<dep_name>` which reduced minimum rust version from 1.60 to 1.58, and also Fedora default dependency resolver should handle it correctly.

**Comment by bgilbert** [comment]
It seems the 2.2.3 `default-devel` package isn't installable:

```console
[root@78f5c3fe9570 /]# dnf install --enablerepo=updates-testing rust-nmstate+default-devel
Fedora 37 - x86_64 - Test Updates               1.4 MB/s | 4.2 MB     00:02    
Last metadata expiration check: 0:00:03 ago on Tue Jan 10 07:44:03 2023.
Dependencies resolved.

 Problem: package rust-nmstate+default-devel-2.2.3-1.fc37.noarch requires crate(nmstate/query_apply) = 2.2.3, but none of the providers can be installed
  - cannot install the best candidate for the job
  - nothing provides crate(nmstate/nispor) = 2.2.3 needed by rust-nmstate+query_apply-devel-2.2.3-1.fc37.noarch
  - nothing provides crate(nmstate/nix) = 2.2.3 needed by rust-nmstate+query_apply-devel-2.2.3-1.fc37.noarch
  - nothing provides crate(nmstate/zbus) = 2.2.3 needed by rust-nmstate+query_apply-devel-2.2.3-1.fc37.noarch
```

I don't think this will affect us once #1038 is applied, but it does affect the currently released version of coreos-installer.

**Comment by bgilbert** [comment]
I've added a commit to #1038 that temporarily enables `updates-testing` to fix CI.  The `default-devel` subpackage should still be fixed upstream, though.

**Comment by bgilbert** [comment]
Automated FailsToInstall BZ for https://github.com/coreos/coreos-installer/issues/1039#issuecomment-1376854497: [#2159314](https://bugzilla.redhat.com/show_bug.cgi?id=2159314)

**Comment by cathay4t** [comment]
The nmstate-2.2.3-2.fc37 and nmstate-2.2.3-2.fc36 fixed the installing problem.
