### ISSUE TITLE
Embedding invalid block-device allowed

### ISSUE THREAD

**Issue by n1ouse** [coreos/coreos-installer#1045]
# Bug #

This might be out of scope but threw me for quite a loop when running into it.

When adding installation arguments to an ISO, or I assume PXE/kargs for that matter, containing a "coreos.inst.install_dev" with an, AFAIK always, invalid block device ending with a '/' character, EG: "/dev/sdX/". It will not inform the user about doing so.

Is this something we would want to filter/parse or warn the user about?

## Target Operating System Version ##
36.20221102.20.0 live iso

## coreos-installer Version ##
0.16.1

**Comment by bgilbert** [comment]
Thanks for the experience report.  I assume you mean that we'd detect this at the `coreos-installer {iso,pxe} customize` stage?  There are a lot of possible configuration errors the user could make during customization, many of which we can't detect, e.g. referencing a nonexistent `/dev/sda` when they meant `/dev/nvme0n1`.  Checking for one specific typo doesn't seem especially useful in that context, so I'll close this for now.

If, instead, you encountered a runtime issue (e.g. you received a confusing error message at installation time), please feel free to reopen.
