### ISSUE TITLE
Installation with --image-file is ignored

### ISSUE THREAD

**Issue by quentin9696** [coreos/coreos-installer#1046]
# Bug #

## Host Operating System Version ##
Container image latest

## Target Operating System Version ##
N/A

## coreos-installer Version ##
Container image latest

## Expected Behavior ##
Do not download the image before installing it

## Actual Behavior ##
It seams to be ignored: 

```
Copying image from /data/image/fedora-coreos-36.20221014.3.1-metal.aarch64.raw.xz
Reading signature from /data/image/fedora-coreos-36.20221014.3.1-metal.aarch64.raw.xz.sig
Read disk 1.2 MiB/633.1 MiB (0%)
Read disk 62.2 MiB/633.1 MiB (9%)
Read disk 84.5 MiB/633.1 MiB (13%)
Read disk 94.8 MiB/633.1 MiB (14%)
Read disk 157.5 MiB/633.1 MiB (24%)
Read disk 164.8 MiB/633.1 MiB (26%)
Read disk 173.5 MiB/633.1 MiB (27%)
Read disk 181.2 MiB/633.1 MiB (28%)
Read disk 190.2 MiB/633.1 MiB (30%)
Read disk 200.0 MiB/633.1 MiB (31%)
Read disk 213.5 MiB/633.1 MiB (33%)
Read disk 224.5 MiB/633.1 MiB (35%)
Read disk 235.0 MiB/633.1 MiB (37%)
Read disk 238.8 MiB/633.1 MiB (37%)
Read disk 241.5 MiB/633.1 MiB (38%)
Read disk 244.8 MiB/633.1 MiB (38%)
Read disk 249.8 MiB/633.1 MiB (39%)
Read disk 254.8 MiB/633.1 MiB (40%)
Read disk 259.8 MiB/633.1 MiB (41%)
Read disk 264.8 MiB/633.1 MiB (41%)
Read disk 268.8 MiB/633.1 MiB (42%)
Read disk 273.5 MiB/633.1 MiB (43%)
Read disk 278.5 MiB/633.1 MiB (43%)
Read disk 279.8 MiB/633.1 MiB (44%)
Read disk 286.5 MiB/633.1 MiB (45%)
Read disk 302.0 MiB/633.1 MiB (47%)
Read disk 322.8 MiB/633.1 MiB (50%)
Read disk 344.2 MiB/633.1 MiB (54%)
Read disk 364.8 MiB/633.1 MiB (57%)
Read disk 384.0 MiB/633.1 MiB (60%)
Read disk 399.8 MiB/633.1 MiB (63%)
Read disk 418.8 MiB/633.1 MiB (66%)
Read disk 440.8 MiB/633.1 MiB (69%)
Read disk 458.2 MiB/633.1 MiB (72%)
Read disk 464.0 MiB/633.1 MiB (73%)
Read disk 467.2 MiB/633.1 MiB (73%)
Read disk 470.5 MiB/633.1 MiB (74%)
Read disk 476.0 MiB/633.1 MiB (75%)
Read disk 477.2 MiB/633.1 MiB (75%)
Read disk 481.0 MiB/633.1 MiB (75%)
Read disk 483.8 MiB/633.1 MiB (76%)
Read disk 487.0 MiB/633.1 MiB (76%)
Read disk 489.8 MiB/633.1 MiB (77%)
Read disk 492.0 MiB/633.1 MiB (77%)
Read disk 495.0 MiB/633.1 MiB (78%)
Read disk 498.8 MiB/633.1 MiB (78%)
Read disk 502.8 MiB/633.1 MiB (79%)
Read disk 507.5 MiB/633.1 MiB (80%)
Read disk 516.2 MiB/633.1 MiB (81%)
Read disk 524.0 MiB/633.1 MiB (82%)
Read disk 532.2 MiB/633.1 MiB (84%)
Read disk 544.0 MiB/633.1 MiB (85%)
Read disk 562.0 MiB/633.1 MiB (88%)
Read disk 570.2 MiB/633.1 MiB (90%)
Read disk 580.5 MiB/633.1 MiB (91%)
Read disk 590.5 MiB/633.1 MiB (93%)
Read disk 601.2 MiB/633.1 MiB (94%)
Read disk 614.8 MiB/633.1 MiB (97%)
Read disk 618.8 MiB/633.1 MiB (97%)
Read disk 621.8 MiB/633.1 MiB (98%)
Read disk 626.8 MiB/633.1 MiB (98%)
Read disk 629.2 MiB/633.1 MiB (99%)
Read disk 633.1 MiB/633.1 MiB (100%)
Read disk 633.1 MiB/633.1 MiB (100%)
Read disk 633.1 MiB/633.1 MiB (100%)
gpg: Signature made Wed Nov  2 15:23:38 2022 UTC
gpg:                using RSA key 53DED2CB922D8B8D9E63FD18999F7CBF38AB71F4
gpg: checking the trustdb
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   4  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 4u
gpg: Good signature from "Fedora (36) <fedora-36-primary@fedoraproject.org>" [ultimate]
Writing Ignition config
Install complete.
```

## Reproduction Steps ##

  1. Download an image using coreos-installer download
  2. Try to install it `podman run --pull=always --privileged --rm -v /dev:/dev -v /run/udev:/run/udev -v "ignition_folder:/data/ignition.ign" -v ${HOME}/test-coreos-cache:/data/image -w /data quay.io/coreos/coreos-installer:release install --image-file /data/image/fedora-coreos-36.20221014.3.1-metal.aarch64.raw.xz -i /data/ignition.ign /dev/sdb`

**Comment by bgilbert** [comment]
What leads you to think the image is being ignored?  The log says it's being used:

```
Copying image from /data/image/fedora-coreos-36.20221014.3.1-metal.aarch64.raw.xz
```

**Comment by quentin9696** [comment]
Hi @bgilbert and thank you for your reply

I'm sorry, I miss some informations: 

Here is the time to download the image: 
`sudo podman run --pull=always --privileged --rm -w /data -v   download   0.31s user 0.21s system 1% cpu 25.971 total `

Here is the time to write an existing image: 
`sudo podman run --pull=always --privileged --rm -v /dev:/dev -v  -v  -v  -w    0.43s user 0.24s system 0% cpu 2:55.60 total`

Anf the time to write an image that's download before: 
`sudo podman run --pull=always --privileged --rm -v /dev:/dev -v  -v  -v  -w    0.44s user 0.25s system 0% cpu 3:00.36 total`

I need 25s to download the image, and the delta between installing the image with two method is only 5s. I'm not sure why there is only 5s between the too, while it should be near 25s. That's why I think there is an issue. 

Maybe I don't understand something during the installation process. 
Also, I'm not sure what `Read disk` log entry are doing.

**Comment by jlebon** [comment]
Hmm, your `podman run` commands look like they weren't pasted correctly.

But to answer your question, "Read disk" is a bit confusing but it's the progress for reading from the source disk image file/URL and writing it to the target block device.

The read/write is done in a streaming manner; coreos-installer decompresses the input stream and writes to the target disk at the same time, so that the full image never has to be stored on-disk first. The reason there is only a 5s difference is likely because network I/O is not the limiting resource (more likely either decompressing on the CPU or writing to the disk).

**Comment by quentin9696** [comment]
@jlebon yeah it's the output of the `time` command. 

Thank you for your explanation. For sur, I use an old usb to sd card adaptor so for sure the network is not the limit resource. Maybe we should change the `Read Disk` to something more explicit, or add something in the documentation

**Comment by bgilbert** [comment]
It says `Read disk` because it's copying the `disk` artifact.  When downloading the PXE image, it'll say `Read initramfs`, `Read rootfs`, and `Read kernel`.

I agree that the message is a bit confusing, but I don't think that's serious enough to be considered a bug, so I'll close this out.  Thanks for reporting, though!
