### ISSUE TITLE
skip_reboot missing from install in CLI

### ISSUE THREAD

**Issue by micheelengronne** [coreos/coreos-installer#112]
# Feature Request #

I would like the possibility to skip_reboot during install via CLI.

**Comment by lucab** [comment]
Thanks for the report.
I'm unfortunately having a bit of trouble trying to understand what's your actual feature request. Could you please add a bit more context about your current usage and where do you feel there is a  gap?

**Comment by micheelengronne** [comment]
I would like to use coreos-installer in a live-config file (a bash script basically). But depending on the server, I would like to be able to do other tasks (in the bash script) after coreos-installer but before rebooting.

**Comment by micheelengronne** [comment]
There seems to not be any arg for skip_reboot here: https://github.com/coreos/coreos-installer/blob/a9a0f2cc7764acbb170cc1fad994a38c3738caf5/src/cmdline.rs#L82

**Comment by lucab** [comment]
`skip_reboot` is an option for the initramfs live-image, which doesn't seem to be your usecase.

My understanding is that you are using the CLI tool directly instead, in your own bash script. In that case there is no implicit reboot, and thus no `skip_reboot` option. Your script can freely take care of running `coreos-installer`, performing additional tasks, and then rebooting (if needed).

**Comment by micheelengronne** [comment]
Really ?! That's great. Thanks. I am just waiting for [that](https://github.com/coreos/coreos-installer/issues/111) and will be more than happy.
