### ISSUE TITLE
signature verification can fail even with `--insecure`.

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#1141]
# Bug #

I'm trying to test out old installs for a bug that I'm investigating. Using the `coreos-installer-0.16.1-2.fc37.x86_64` coreos-installer I get a failure even with `--insecure`.

I know we rotated out the F35 key long ago, but still am thinking `--insecure` should have done the trick here.

```
$ sudo ./coreos-installer install --architecture=aarch64 -i config.ign $FCOSDISK -f ./fedora-coreos-35.20211119.3.0-metal.aarch64.raw.xz --insecure
Copying image from ./fedora-coreos-35.20211119.3.0-metal.aarch64.raw.xz
Reading signature from ./fedora-coreos-35.20211119.3.0-metal.aarch64.raw.xz.sig
> Read disk 582.3 MiB/582.3 MiB (100%)   
gpg: Signature made Sat 04 Dec 2021 03:39:42 PM EST
gpg:                using RSA key 787EA6AE1147EEE56C40B30CDB4639719867C58F
gpg: Can't check signature: No public key

Error: GPG verification failure

Resetting partition table
Error: install failed
```

Maybe I'm doing something wrong?j

## Host Operating System Version ##

Fedora 37

## coreos-installer Version ##

`coreos-installer-0.16.1-2.fc37.x86_64`

## Expected Behavior ##

Skip signature verification

## Actual Behavior ##

Fails

## Reproduction Steps ##

See description

**Comment by bgilbert** [comment]
The semantics of `--insecure` are that it ignores missing signatures, not unverifiable ones.  That's intentional, but the help text says `Skip signature verification`, which is certainly misleading.

**Comment by dustymabe** [comment]
OK. Given your clues the workaround is easy:

```
$ rm ./fedora-coreos-35.20211119.3.0-metal.aarch64.raw.xz.sig
```

but it certainly wasn't obvious :)

Not sure if there's much we can do here. Feel free to close.

**Comment by bgilbert** [comment]
#1142 clarifies the help text.  Thanks for pointing this out.

**Comment by jlebon** [comment]
Hmm, there's a UX issue though when it's coreos-installer that downloads the signature:

```
$ coreos-installer download --decompress --insecure --image-url \
    https://builds.coreos.fedoraproject.org/prod/streams/next/builds/32.20200416.1.0/x86_64/fedora-coreos-32.20200416.1.0-qemu.x86_64.qcow2.xz
Downloading image from https://builds.coreos.fedoraproject.org/prod/streams/next/builds/32.20200416.1.0/x86_64/fedora-coreos-32.20200416.1.0-qemu.x86_64.qcow2.xz
Downloading signature from https://builds.coreos.fedoraproject.org/prod/streams/next/builds/32.20200416.1.0/x86_64/fedora-coreos-32.20200416.1.0-qemu.x86_64.qcow2.xz.sig
> Read disk 477.2 MiB/477.2 MiB (100%)
gpg: Signature made Thu Apr 16 19:36:09 2020 UTC
gpg:                using RSA key 50CB390B3C3359C4
gpg: Can't check signature: No public key
Error: GPG verification failure
$ echo $?
1
$ ls *.qcow2
ls: cannot access '*.qcow2': No such file or directory
```

There's no way for me to tell coreos-installer to not download the signature.

**Comment by bgilbert** [comment]
Hmm, true.  Does that matter?  The affected case is downloading an ancient image by URL, which is an unusual thing to do, and signature verification is the main benefit of `coreos-installer download` over `curl`/`wget`.

**Comment by dustymabe** [comment]
yeah I don't think we need to go out of our way to solve this problem. I was just confused initially and now I'm not :)

**Comment by jlebon** [comment]
> Hmm, true. Does that matter? The affected case is downloading an ancient image by URL, which is an unusual thing to do, and signature verification is the main benefit of `coreos-installer download` over `curl`/`wget`.

I use it for its streaming decompression. :) I can do this with `curl | unxz > ...` but that isn't as ergonomic.

I'm OK not trying to cater to this.
