### ISSUE TITLE
quay: release tag needs to be updated

### ISSUE THREAD

**Issue by lucab** [coreos/coreos-installer#116]
I've just finished [releasing](https://github.com/coreos/coreos-installer/issues/114) version 0.1.1, but due to missing permission I was unable to update the quay.io `release` container tag to point to `0.1.1`.

For the time being the latest release should be consumed directly as `quay.io/coreos/coreos-installer:v0.1.1`.

Once @bgilbert is back we will update the tag and double-check repository ACLs.

**Comment by lucab** [comment]
Got access to the repo in the meanwhile, `release` tag updated.

**Comment by dustymabe** [comment]
nice work @lucab
