### ISSUE TITLE
combine image options - apply sanity checking

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#117]
Right now we have: 

```
    -u, --image-url <URL>          Manually specify the image URL                   
    -f, --image-file <path>        Manually specify a local image file
```

It seems like it would be reasonable to use a single option and support either a URL or a local path to a file being passed.

**Comment by dustymabe** [comment]
@lucab @jlebon @bgilbert - WDYT? I'm thinking we just have: 

```
-f, --image-file <path|URL> Manually specify a local image file path or remote image file URL
```

**Comment by jlebon** [comment]
Seems reasonable to me.

**Comment by lucab** [comment]
Not against this on principle, but I'm not sure that `--image-file https://...` is less confusing.

What's the problem we are having with the current CLI? Is it a UX hurdle or just a cosmetic for `--help`?

**Comment by dustymabe** [comment]
> Not against this on principle, but I'm not sure that `--image-file https://...` is less confusing.

Maybe `--image <path|URL>` would be better, but ignition is currently squatting on the `-i` short option. 

> 
> What's the problem we are having with the current CLI? Is it a UX hurdle or just a cosmetic for `--help`?

I think both. You'd never specify both `--image-file` and `--image-url` to a single invocation and they both specify the image, just different ways of retrieving it, which is encoded in the value passed to the option.

**Comment by bgilbert** [comment]
`https://example.com/config.ign` is a valid filename.  `./https://example.com/config.ign` is a valid workaround, but that creates obligations for the calling code.

More generally: if we combined the two options, there are conceivable use cases where calling code might need to do extra validation of user-provided filenames and URLs, and that validation would need to match coreos-installer's parser in all cases.  That doesn't seem worth it to me.

**Comment by dustymabe** [comment]
> `https://example.com/config.ign` is a valid filename. `./https://example.com/config.ign` is a valid workaround, but that creates obligations for the calling code.
> 
> More generally: if we combined the two options, there are conceivable use cases where calling code might need to do extra validation of user-provided filenames and URLs, and that validation would need to match coreos-installer's parser in all cases. That doesn't seem worth it to me.

It feels like we're overcomplicating things. I was thinking all that we'd do is the equivalent of `test -f $image && imageisfile=true || imageisurl=true`. if the value passed in by the user doesn't match a file that exists on disk then assume it's a URL. This logic should sufficiently handle a file at `./https://example.com/config.ign`

**Comment by bgilbert** [comment]
Then a typoed filename would be treated as a URL, in which case the installer would produce a confusing error message.  Unless we special-cased that in turn.

My point: file paths and URLs are different.  If we try to automagically detect which one we're dealing with, we'll have a string of corner cases like this, and opportunities for user confusion.  AFAICT it's simpler, cleaner, and safer for the user to tell us what they're giving us.  What's the benefit to combining these options?

**Comment by jlebon** [comment]
FWIW, I don't think it's super uncommon to do the "auto-detect" stuff. For example, both rpm-ostree and dnf will auto-detect whether the provided package to `$pkgmgr install` is a generic request (`strace`), a local RPM (`strace.rpm`), or a remote RPM (`http://localhost/strace.rpm`).

That said, I think I agree now with Benjamin that we shouldn't combine them for the installer. For one thing, rpm-ostree has a D-Bus API (and dnf has a Python API), through which one can say precisely what one wants. OTOH, `coreos-installer` just has the CLI, so it makes sense to me to keep it formal and precise.

**Comment by dustymabe** [comment]
> Then a typoed filename would be treated as a URL, in which case the installer would produce a confusing error message. Unless we special-cased that in turn.
> 
> My point: file paths and URLs are different. If we try to automagically detect which one we're dealing with, we'll have a string of corner cases like this, and opportunities for user confusion. 

Then it's just another check for the the argument starting with `http(s)`?

> AFAICT it's simpler, cleaner, and safer for the user to tell us what they're giving us. What's the benefit to combining these options?

It's mostly my personal preference to dedup two redundant options. You'll never use them both at the same time and they point to the same input. The argument can easily be checked to determine which "mode" we're in. I'm usually the person that is arguing *for* being explicit, but in this case it's an easy win and I really don't think there are any significant drawbacks.

So let's say we do add url support for ignition. If we keep options separate we'll end up with:
- `--image-url`
- `--image-file`
- `--ignition-url`
- `--ignition-file`

When really all of those can be handled by `--ignition` and `--image` (unfortunately the `-i` short option would conflict).

**Comment by dustymabe** [comment]
> That said, I think I agree now with Benjamin that we shouldn't combine them for the installer. For one thing, rpm-ostree has a D-Bus API (and dnf has a Python API), through which one can say precisely what one wants. OTOH, `coreos-installer` just has the CLI, so it makes sense to me to keep it formal and precise.

+1 - We can close this out.
