### ISSUE TITLE
support running via CLI invocation

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#14]
Right now we are running from the initramfs and only parsing kernel command line arguments to do an install. We should support running via a CLI invocation. Something like:

```
coreos-installer --install-dev sda --image-url http://example.com --ignition-url http://example.com
```

When this is done we can fill out the docs: https://github.com/coreos/coreos-installer#testing-out-the-installer-script-by-running-it-directly

**Comment by arithx** [comment]
Closed in #16

**Comment by dustymabe** [comment]
one thing I will note is that I didn't test executing via the CLI directly (i.e. targeting an unused disk from a booted system). @arithx - can you confirm you did?

**Comment by arithx** [comment]
With my testing I was booting the kernel & initramfs.img directly via virt-install and installing over `/dev/vda` (both via the kcmdline args as well as letting it drop to emergency shell & running the script by hand)

**Comment by jlebon** [comment]
I think this ticket is about actually running the installer directly from the CLI from a fully booted system though, no?

Let's say an acceptance criteria for this ticket should be that https://github.com/coreos/coreos-installer#testing-out-the-installer-script-by-running-it-directly is filled out with instructions that work?

**Comment by dustymabe** [comment]
> I think this ticket is about actually running the installer directly from the CLI from a fully booted system though, no?

AFAIU that should work as long as you are targeting a disk that isn't currently booted off of 

> 
> Let's say an acceptance criteria for this ticket should be that https://github.com/coreos/coreos-installer#testing-out-the-installer-script-by-running-it-directly is filled out with instructions that work?

👍 - @arithx - WDYT?

**Comment by arithx** [comment]
> I think this ticket is about actually running the installer directly from the CLI from a fully booted system though, no?

That should be doable with the current setup (it allows for the three kcmdline args to be overridden via flags) but I haven't tested that.

> > Let's say an acceptance criteria for this ticket should be that https://github.com/coreos/coreos-installer#testing-out-the-installer-script-by-running-it-directly is filled out with instructions that work?
> 
> 👍 - @arithx - WDYT?

Fair, I'll re-open.

**Comment by dustymabe** [comment]
docs are part of PR https://github.com/coreos/coreos-installer/pull/35 - so this should be fixed when that merges

**Comment by arithx** [comment]
#35 has merged, closing
