### ISSUE TITLE
install: check Ignition config hash

### ISSUE THREAD

**Issue by lucab** [coreos/coreos-installer#142]
# Feature Request #

It would be nice to teach `coreos-installer install` to check the hash of the input Ignition configuration, in order to ensure configuration integrity.
This could be especially helpful for configurations that are fetched from external systems, either directly by `coreos-installer` or by a pre-fetching step.

## Strawman proposal ##

Add an `--ignition-hash <arg>` flag to `coreos-installer install`. By default this is not provided by the user and results in no hash checking.

Accept an input argument in the form of `$type-$digest`, for some sane set of hash types (this matches Ignition `verification.hash` syntax). When passed by the user, it introduces a mandatory hash-matching check before embedding the config.

If we later go for https://github.com/coreos/coreos-installer/issues/118 and we augment `coreos-installer install` to fetch remote Ignition configs, we can print a warning or hard-fail when we hit the "remote config but no hash" case.

**Comment by dustymabe** [comment]
I think this mostly sums it up. A bit of bikeshedding, though. `--ignition-checksum` maybe? Also I prefer `$type:$digest` but if ignition already has precedent of a way to do it then I think it makes sense to re-use that.

**Comment by lucab** [comment]
@dustymabe in the end (https://github.com/coreos/coreos-installer/pull/178) I kept it as close as possible to Ignition, which means:
 * name is `--ignition-hash`, which mirrors Ignition field name `ignition.config.verification.hash`
 * value is `<type>-<value>`, which mirrors Ignition field value format
