### ISSUE TITLE
pxe install not working with the stable 31.20200113.3.1 version

### ISSUE THREAD

**Issue by lfarkas** [coreos/coreos-installer#144]
we try the pxe install both on bare metal and virt-manager and neither works. it's always give us a enter maintenance mode with this menu
```
label fedora-coreos-virt
	menu label Fe^dora CoreOS Virt
	kernel CoreOS/fedora-coreos-live-kernel-x86_64
	append initrd=CoreOS/fedora-coreos-live-initramfs.x86_64.img ip=dhcp nomodeset rd.neednet=1 audit=0 console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=/dev/vda coreos.inst.image_url=ftp://mirror/download/mirror/coreos/fedora-coreos-metal.x86_64.raw.xz coreos.inst.ignition_url=skip
```
we tried both `coreos.inst.install_dev=/dev/vda` and `coreos.inst.install_dev=vda`. The same happened with sda too.

**Comment by lucab** [comment]
Thanks for the report.

Once in emergency mode, what does `sudo journalctl -u coreos-installer.service` say?

Additionally, can you please try with an HTTP transport instead of FTP?

**Comment by lfarkas** [comment]
- site a side note i turn off all audit message just because otherwise the screen is unreadable.
- another note sudo don't required in this case.
- without --no-hostname the end not readable.
and the error cause was that the signature fetch failed (would be useful to document) and neither --insecure specified.

how can i specify --insecure in pxe?

**Comment by bgilbert** [comment]
You can pass `coreos.inst.insecure`.  But you shouldn't do that.  Instead, ensure that your mirror includes the GPG signature for the install image.

**Comment by lfarkas** [comment]
ok thanks I fixed it and pull the .sig files too. but it'd be useful to show something on the console to know what;s the problem. 
imho find out `journalctl -u coreos-installer.service` is not too easy:-)

**Comment by bgilbert** [comment]
Yup, good point.  Filed as https://github.com/coreos/coreos-installer/issues/145.
