### ISSUE TITLE
http/https proxy support?

### ISSUE THREAD

**Issue by bcg62** [coreos/coreos-installer#152]
does this support using proxy? It doesn't seem to work using standard env vars.

**Comment by lucab** [comment]
I think the latest release does not pick up standard env vars, but the current master branch should be fine. https://github.com/coreos/coreos-installer/pull/141 is the PR who changed that.

If you are using `coreos-installer` from a container, `quay.io/coreos/coreos-installer:master` should already work. It would be great if you could confirm it, as I don't have a proxied environment at hand to double-check.

Please do note that for `NO_PROXY` we'll have to wait for https://github.com/seanmonstar/reqwest/issues/705.

**Comment by bcg62** [comment]
I can confirm its working on master. Thanks!
