### ISSUE TITLE
coreos-installer-service doesn't support multiple ip kargs for firstboot

### ISSUE THREAD

**Issue by sebastienGuavus** [coreos/coreos-installer#156]
# Bug #

## Host Operating System Version ##
fedora-coreos-31

## Target Operating System Version ##
fedora-coreos-31

## coreos-installer Version ##
coreos-installer 0.1.2

## Expected Behavior ##
If I provide multiple ip kargs all are save for firstboot

## Actual Behavior ##
Only last ip kargs is saved

## Reproduction Steps ##

  1. ...
  2. ...

## Other Information ##

This apply to all others kargs in PERSIST_DRACUT_NET_PARAMS that could reasonably be specified more than once.

```bash
karg() {
    local name="$1" value=""
    for arg in "${cmdline[@]}"; do
        if [[ "${arg%%=*}" == "${name}" ]]; then
            if [[ -z ${value} ]]; then
                value="${arg#*=}"
            else
	        value="${value} ${arg#*=}"
            fi		
        fi
    done
    echo "${value}"
}
```

**Comment by bgilbert** [comment]
Thanks for the report.  This is a regression from the legacy branch.

**Comment by sebastienGuavus** [comment]
The snippet above doesn't work. Should be more like
```
    else
       value="${value} {$name}=${arg#*=}"
    fi
```
But then it could cause issue for karg_bool or if any of the coreos.inst.* karg are pass more than once.
Maybe a kargs function ?
