### ISSUE TITLE
detect networking kcmdline args and write them to a file

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#17]
If someone provides static networking configuration via the kernel command line for the run of the installer then it would be nice if we persist those kernel command line options into the first boot of the real machine (as networking configuration that is done via ignition will not apply to the initramfs where the embedded ignition config may have references to external resources).

One way we could implement something like this is by detecting these options (we'll want to be selective about which ones we propagate) and then add them to the kernel command line on first boot just like we do for `ignition.firstboot` using: 

https://github.com/coreos/ignition-dracut/blob/b11553f9e2b530fbbb5a2504bc72b364829c879c/grub/02_ignition_firstboot#L1-L13

**Comment by dustymabe** [comment]
I have a good idea of how half of this could be pulled off (i.e. the dynamically picking up kernel command line args from boot partition during grub).

if someone else could concentrate on the 'detect kernel command line args and write them to a file during install' part then I think we'll be close to having something that works.

**Comment by arithx** [comment]
@dustymabe the kernel command line arg detection should be as simple as adding them to [parse-coreos.sh](https://github.com/coreos/coreos-installer/blob/master/dracut/30coreos-installer/parse-coreos.sh#L6-L11), and writing them to the real root [is already done for the Ignition snippet](https://github.com/coreos/coreos-installer/blob/master/coreos-installer#L313-L317) so that should be a simple addition as well.

**Comment by dustymabe** [comment]
ok as mentioned in https://github.com/coreos/coreos-installer/issues/17#issuecomment-475391409 let's tackle this in two parts:

- detecting kernel args and writing them to a file during run of installer
- picking up kernel args from file on first boot

Since we are already adding network config options for ignition first boot in the [ignition-dracut grub snippet](https://github.com/coreos/ignition-dracut/blob/b11553f9e2b530fbbb5a2504bc72b364829c879c/grub/02_ignition_firstboot#L1-L13) I think we should implement this over in ignition-dracut. 

For the ignition-dracut part I opened https://github.com/coreos/ignition-dracut/issues/64. For the coreos-installer part we'll let this ticket track that work.

**Comment by arithx** [comment]
Do we have any opinions on what set of networking args we want to be persisting? Should we just pass through all of the [dracut networking args](https://www.mankier.com/7/dracut.cmdline#Description-Network)?

cc @bgilbert

**Comment by bgilbert** [comment]
I guess we should whitelist all of the dracut networking options.  I'd prefer to keep the set minimal so users don't start relying on arbitrary kcmdline args, but we don't want to discover after shipping that another networking option is needed for particular setups.

**Comment by dustymabe** [comment]
ok, just tested out #18 - at a minimum we at least need to be able to set a nameserver and have that propagate forward too I would think

**Comment by arithx** [comment]
@dustymabe I'm in the process of updating the patch to support all of the dracut networking arguments.
