### ISSUE TITLE
coreos.inst.mount={device1},{device2}

### ISSUE THREAD

**Issue by JoelKessler** [coreos/coreos-installer#174]
# Feature Request #
## Desired Feature ##
The coreos-installer service should accept an additional kernel parameter: 

> coreos.inst.mount={device1},{device2},...

This parameter will mount the defined additional devices before executing the coreos-installer.

The mount endpoint should be:
/mnt/{device1}, /mnt/{device2}
## Other Information ##
This would allow a fully automated installation from a single USB or DISK.

As for example:
I have the USB device:
sda
- sda1

sda1 contains the live ISO installation file (created via example rufus). 

If I now would extend my grub.cfg file like this: (menuentry, linux /images/vmlinuz {parameters})

> ignition.firstboot ignition.platform.id=metal coreos.inst.mount=/dev/sda1 coreos.inst.ignition_url=file://mnt/sda1/ignition/ignition.ign coreos.inst.install_dev=/dev/nvme0n1 coreos.inst.image_url=file://mnt/sda1/images/fedora_coreos.raw.xz coreos.inst=yes coreos.inst.insecure

It would fully install everything from the disk sda1 to nvme0n1.

Process:
1. Create USB with eg. Rufus from FCOS live image
2. Add some folders on USB or files which I want to access from the installer.
3. Boot from USB on HW with the above defined kernel parameters
4. The system will be installed and reboot without having any internet connection.

## Notes ##
Origin: https://lists.fedoraproject.org/archives/list/coreos@lists.fedoraproject.org/thread/IQVURC6ROXQTT32KYJN2ZT2LI6XXH3MU/

**Comment by bgilbert** [comment]
The live ISO now includes a packed version of the install image, so installs no longer require network access.

As to the broader issue, we'd like to avoid adding additional `coreos.inst` command-line arguments.  However, we now have `coreos-installer iso customize`, which provides various mechanisms for customizing the ISO image.  You could use `--live-ignition` to add an Ignition config that enables a systemd mount unit that mounts the USB stick, plus `--installer-config` to pass a [config file](https://coreos.github.io/coreos-installer/customizing-install/#config-file-format) that references files on that stick.

I'll go ahead and close this out.  Thanks for reporting.
