### ISSUE TITLE
Fedora CoreOS ISO 'Error aa00 reading sector' in Dell baremetal server

### ISSUE THREAD

**Issue by e-minguez** [coreos/coreos-installer#2]
I've tried to boot the ISO in a baremetal server (Dell r703xd) via virtual media and it fails to start with some ' Error aa00 reading sector' messages. See https://youtu.be/8d_LPsljEjw (I've tried with and without `coreos.inst.*` options)

I've used:

- https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/fedora-coreos-29.669.iso
- `coreos.inst.install_dev=sda coreos.inst.image_url=https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/fedora-coreos-29.669-metal-bios.raw.gz coreos.inst.ignition_url=http://10.19.138.7/b.ign`
- b.ign content:

```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "storage": {
    "disks": [
      {
        "device": "/dev/sda",
        "wipeTable": true,
        "partitions": [
          {
            "label": "ROOT",
            "number": 0,
            "size": 0,
            "start": 0
          }
        ]
      }
    ],
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/sudoers.d/core",
        "mode": 440,
        "contents": { "source": "data:,core%20ALL%3D%28ALL%29%20NOPASSWD%3A%20ALL" }
      }
    ]
  },
  "systemd": {},
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa REDACTED\n"
        ]
      }
    ]
  }
}
```

**Comment by e-minguez** [comment]
I've also tried with a VM... where the installation finish successfully but:

- After the installation, it hangs with the `Probing EDD (edd=off to disable)...ok` message
- I've tried [this](https://access.redhat.com/solutions/47621) workaround (tl;dr.- add `edd=off` at the kernel line in grub)

Minor gotcha:
- `A start job is running for CoreOS Installer (xmin ys / no limit)` message appears during all the installation process so you cannot see the progress bar (actually, it flickers between the progress bar and the message).
![progressbar](https://user-images.githubusercontent.com/346758/53107644-b9e76800-3535-11e9-854a-49cb885526bd.png)

I've used:

- Fedora 29 host, kvm + virt-manager
- https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/fedora-coreos-29.669.iso
- `coreos.inst.install_dev=vda coreos.inst.image_url=https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/fedora-coreos-29.669-metal-bios.raw.gz coreos.inst.ignition_url=http://10.19.138.7/v.ign`
- v.ign content:

```
{
  "ignition": {
    "config": {},
    "security": {
      "tls": {}
    },
    "timeouts": {},
    "version": "2.2.0"
  },
  "storage": {
    "disks": [
      {
        "device": "/dev/vda",
        "wipeTable": true,
        "partitions": [
          {
            "label": "ROOT",
            "number": 0,
            "size": 0,
            "start": 0
          }
        ]
      }
    ],
    "files": [
      {
        "filesystem": "root",
        "path": "/etc/sudoers.d/core",
        "mode": 440,
        "contents": { "source": "data:,core%20ALL%3D%28ALL%29%20NOPASSWD%3A%20ALL" }
      }
    ]
  },
  "systemd": {},
  "networkd": {},
  "passwd": {
    "users": [
      {
        "name": "core",
        "sshAuthorizedKeys": [
          "ssh-rsa REDACTED\n"
        ]
      }
    ]
  }
}
```

**Comment by dustymabe** [comment]
so VM works - bare metal fail. I'll try on some real hardware. If you have any other hardware (different profile) to try it on to see if it is specific to one platform that would help.
