### ISSUE TITLE
install: UI for forwarding network information into next boot 

### ISSUE THREAD

**Issue by dustymabe** [coreos/coreos-installer#205]
Right now I'm working on an interactive experience for users to configure networking of the system in the booted Live ISO right before they run `coreos-install install`. As a user I'm currently:

- getting the system booted up (no DHCP) to boot prompt
- running `nmtui` to configure networking and gain internet access
- run curl to grab ignition config
- run coreos-installer to install to disk
- reboot

I need to be able to take the networking information from the current system (for FCOS it would be `/etc/NetworkManager/system-connections`) into the initramfs of the firstboot. My current thinking is that we just copy the files from `/etc/NetworkManager/system-connections` into a directory in the boot partition like we do for other things and then have a systemd unit that runs in the initramfs to pick that information up and carry it forward.

Assuming that all sounds good what do we want the UI for this to look like? One option:

- `coreos-installer install --forward-networking[=/etc/NetworkManager/system-connections]`
    - defaults to `/etc/NetworkManager/system-connections` but directory can be overridden
    - the option could be `--networking-files=` instead maybe?

Another option is that we make this more generic and make `--initramfsfiles=/path/to/initramfs/rootfs` and make a generic way to copy files into the initramfs environment but I don't know how much we should support something like this.

Thoughts?

**Comment by dustymabe** [comment]
Talking with @bgilbert on this topic I think we settled on something like

- short option `-n`
- long option `--forward-networking-files`
- the options optionally accept a value that is a path to a directory where the networking files are located
    - defaults to `/etc/NetworkManager/system-connections`

**Comment by bgilbert** [comment]
I'm so-so on `--forward-networking-files`.  "files" are an implementation detali.  `--copy-network-config`?

**Comment by dustymabe** [comment]
I could go either way on those two. As long as you're still OK with the optional accepting a `/path/to/networking/config/files/` to override the default.

**Comment by jlebon** [comment]
Could also be a more generic `--copy-config /etc/subpath`.

**Comment by bgilbert** [comment]
@jlebon, I think going that far would start encouraging users to bypass Ignition.

**Comment by jlebon** [comment]
Yeah, true. Though on that note, maybe what we actually want is to have whatever wraps NetworkManager-tui to spit out an Ignition config that can be merged into the main config (could easily build that functionality on top of https://github.com/coreos/fcct/issues/83).

That way users have the canonical config to use for future automated re-installs (and also for other bare metal hosts that need installing if the network config isn't inherently node-specific).

**Comment by jlebon** [comment]
> Though on that note, maybe what we actually want is to have whatever wraps NetworkManager-tui to spit out an Ignition config that can be merged into the main config (could easily build that functionality on top of coreos/fcct#83).

Though reading https://github.com/coreos/coreos-installer/issues/205#issue-593025898 again, it seems like we're not planning on wrapping `nmtui` anymore, right?

So yeah, maybe this is too much friction and `--copy-network-config` is fine. Though would be cool to document the "discovery" path too of just using the live ISO to generate the keyfiles and converting them into an Ignition config.

**Comment by dustymabe** [comment]
> Though would be cool to document the "discovery" path too of just using the live ISO to generate the keyfiles and converting them into an Ignition config.

The problem with that is that the ignition config could have remote references so we need the networking in the initramfs.
