### ISSUE TITLE
docs: examples using `coreos-installer iso` subcommands

### ISSUE THREAD

**Issue by miabbott** [coreos/coreos-installer#207]
The use of `iso embed` to generate unique ISOs for installing FCOS/RHCOS in large bare metal deployments is likely going to be an important use case as we move forward.

We should have some clear documentation and examples of how one could use this ability to generate ISOs that would be possible of self-installing.  (i.e. embed an Ignition config containing a systemd unit that would kick off `coreos-install`)

**Comment by bgilbert** [comment]
This can be done now via the `--dest-ignition` and/or `--dest-device` arguments to `coreos-installer iso/pxe customize`.  We have [upstream docs](https://coreos.github.io/coreos-installer/customizing-install/#creating-customized-iso-and-pxe-images) and [FCOS docs](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_customizing_installation) and will soon have OCP docs.  I'll go ahead and close this out.
