### ISSUE TITLE
Consider using mount namespaces

### ISSUE THREAD

**Issue by jlebon** [coreos/coreos-installer#208]
In the various parts in which we mount partitions to read or write files into, consider using a mount namespace instead if supported since we normally require root anyway in most of those workflows. That way we guarantee that the mounts are just for us. This applies at least to `coreos-install install` and `coreos-install osmet pack`.

**Comment by dustymabe** [comment]
This is probably safe to do when we run from our Live Images. Any perceived problems when running from the container or just directly on XYZ distro?

**Comment by jlebon** [comment]
Yeah, we would definitely want to gracefully fallback to the current behaviour if we error out because of permissions or missing support along the way.
