### ISSUE TITLE
Metal-bios and Metal-uefi images do not boot after install

### ISSUE THREAD

**Issue by yuqi-zhang** [coreos/coreos-installer#22]
Using the `iso` + `bios/uefi` image from https://ci.centos.org/artifacts/fedora-coreos/prod/builds/latest/ and following: https://github.com/coreos/coreos-installer#using-the-installer-on-fcos-or-rhcos, the installed FCOS does not seem to boot correctly. More specifically, the install to disk seems to happen correctly, and then upon reboot, shows the bootmenu, and then hangs shortly thereafter with no messages etc.

Ignition conf: 
```
{"ignition":{"config":{},"security":{"tls":{}},"timeouts":{},"version":"3.0.0"},"networkd":{},"passwd":{"users":[{"groups":["sudo"],"name":"core","sshAuthorizedKeys":["ssh-rsa ...]}]},"storage":{},"systemd":{}}
```

Note that I've seen similar issue with ignition v2s3 in RHCOS before as well, the `ova` and `ami` still work correctly, but an `iso` installed image does not. (Not sure if this is an actual error with the installer or somewhere else.)

**Comment by jlebon** [comment]
Hmm, did you check if the serial console showed any error message? I tried this locally (though just the bios image) and it worked *but* I essentially hit https://github.com/coreos/coreos-assembler/pull/339. I.e. I had to add `ignition.platform.id=metal` so that Ignition didn't die.

**Comment by yuqi-zhang** [comment]
Can confirm https://github.com/coreos/coreos-assembler/pull/339 fixes the issue, closing

**Comment by jcordes73** [comment]
I was playing around with the console kernel boot parameters, changing

console=ttyS0,115200n8

to

console=ttyS0 console=tty0

Unfortunately I have to do this change after every install, as there is not way I can set the kernel parameters for the next boot. But I have seen that https://github.com/coreos/coreos-installer/issues/13 has been opened for this.

**Comment by jlebon** [comment]
https://github.com/coreos/coreos-assembler/pull/473

**Comment by jcordes73** [comment]
Tested with 29.936 and it is working, i.e. I get log output on the console.
