### ISSUE TITLE
Follow-ups to osmet

### ISSUE THREAD

**Issue by jlebon** [coreos/coreos-installer#224]
Tracker issue to jot down follow-up patches for [osmet](https://github.com/coreos/coreos-installer/pull/187) before we forget about them.

- [x] finish plumbing through metal4k - https://github.com/coreos/coreos-assembler/pull/1501
- [x] support for RHCOS' cipher_null LUKS container - https://github.com/coreos/coreos-installer/pull/251
- [ ] #1034
- [ ] #1035

**Comment by dustymabe** [comment]
> * opportunistically use osmet even when `--stream` is provided if the artifact matches the osmet version.

my interpretation of this: "if $stream version on remote servers matches the embedded content version then opportunistically use the embedded content rather than pulling file from remote". Is that correct?

**Comment by jlebon** [comment]
> my interpretation of this: "if $stream version on remote servers matches the embedded content version then opportunistically use the embedded content rather than pulling file from remote". Is that correct?

Yup, exactly!

**Comment by cgwalters** [comment]
> support for RHCOS' cipher_null LUKS container.

I'm taking this.

**Comment by bgilbert** [comment]
Moved the remaining items to #1034 and #1035.
