### ISSUE TITLE
warn/error if disk image is not gzipped

### ISSUE THREAD

**Issue by miabbott** [coreos/coreos-installer#24]
The installer appears to happily consume `.raw` disk images with no indication that anything is going wrong...until you try to boot your host.

It would be grand if the installer could warn the user or error out with some kind of message about requiring gzipped images.

Granted, I don't know if this would be useful in the automated case, but I figure it is worth starting the conversation here.

**Comment by jlebon** [comment]
Alternatively, just pass it straight through in that case. That way we accept both gzipped and non-gzipped images.

There's also a related UX issue with the way the images are downloaded. RHCOS should hopefully be fixed soon so it no longer recommends decompressing the images on download. FCOS is already "fixed", though we'll want to make sure we don't regress when moving to cloud storage.

**Comment by zshi-redhat** [comment]
@miabbott  @jlebon   Does it matter if the gzipped image is named as xx.raw?  Will it still be able to deploy successfully?
I'm using the gzipped image with name metal-bios.raw, hit an error below, is it related to this issue?
```
[   91.730207] systemd[1]: dev-disk-by\x2dlabel-boot.device: Job dev-disk-by\x2dlabel-boot.device/start timed out.
[   91.732920] systemd[1]: Timed out waiting for device dev-disk-by\x2dlabel-boot.device.
[   91.736221] systemd[1]: Dependency failed for Ignition (setup).
[   91.739338] systemd[1]: Dependency failed for Ignition Complete.
[   91.742479] systemd[1]: Dependency failed for Initrd Default Target.
[   91.745810] systemd[1]: initrd.target: Job initrd.target/start failed with result 'dependency'.
[   91.747799] systemd[1]: initrd.target: Triggering OnFailure= dependencies.
[   91.749225] systemd[1]: ignition-complete.target: Job ignition-complete.target/start failed with result 'dependency'.
```

**Comment by jlebon** [comment]
@zshi-redhat No, it shouldn't actually matter what the file name is. Maybe let's keep the discussion in one place over in https://github.com/coreos/ignition-dracut/issues/68 since there's already more details there (though do file future installer-related bugs in this repo!).

**Comment by arithx** [comment]
I think we can just add `-f` to the `zcat` call and it should do the pass-through for raw content.
