### ISSUE TITLE
install `--insecure` was not respected when using local image source?

### ISSUE THREAD

**Issue by junjiequ** [coreos/coreos-installer#273]
I am trying to install CoreOs built from `testing-devel` branch of fedora-coreos-config.

The installation is in "offline mode". So the ignition file were built into the live iso file using the `iso embed` and the raw image (together with the signature and pub key) was grown into it as well (using dvd+rw-tools). 

The layout of the files in iso image looks like below:
```text
Directory listing of /CUSTOM/
d---------   0    0    0            2048 Jun 18 2020 [ 353848 02]  .
d---------   0    0    0            2048 Jun 18 2020 [ 353847 02]  ..
----------   0    0    0       530651880 Jun 18 2020 [ 353854 00]  IMG_RAW.XZ;1
----------   0    0    0             588 Jun 18 2020 [ 612962 00]  IMG_RAW_XZ.SIG;1
----------   0    0    0            3147 Jun 18 2020 [ 612963 00]  IMG_RAW_XZ.PUB;1
```
coreos-installer will be invoked to kick off the installation.  The command I use is:
```bash
coreos-installer install --firstboot-args console=tty0 --image-file /run/media/iso/custom/img_raw.xz --insecure --ignition /home/core/config/ign /dev/sda
```
I can see from the terminal that the images are read from disk till 100%.
Then the next line after *100%* was to start the **gpg-verify** process.

The reason I specified **--insecure** was because I don't want it to verify the signature just yet - even thought the signature and pub key were there.

**BUG?**  I thought if --insecure was used, then the image source signature verification would be skipped? Am I wrong here? or is it a bug?

I looked into the code - the signature's default path is {img_path}.sig, which I guess that's why the program is trying to load the signature by default. 

[**Question**] Just trying to help myself understand: the signature will still be loaded even --insercure is specified, right?

Because the public key I used to generate that signature was not imported  - hence the validation failed. 

That's why the installation has failed with error: "gpg: Can't check signature: No public key".

My last **[question]** is: unlike the .sig file for the signature, 3rd party public key will not be used automatically, is that right?

Thanks in advance for the clarification.

**Comment by cgwalters** [comment]
You don't need to worry about building a separate DVD now that [osmet has landed](https://github.com/coreos/coreos-installer/pull/187).  See also https://github.com/coreos/fedora-coreos-config/pull/233 which is exactly what you're doing, but was removed in https://github.com/coreos/coreos-assembler/pull/1418 in favor of osmet.

**Comment by cgwalters** [comment]
Just stop passing `--image-file` or `--image-url` etc. to `coreos-installer` and it will use osmet automatically.

(There's no need to verify GPG here because the content came from the same place as the ISO)

**Comment by bgilbert** [comment]
To answer your question, `--insecure` allows the signature to be missing, but we always verify the signature if one is present.  And there's currently no way to provide a different public key, other than recompiling coreos-installer.

**Comment by junjiequ** [comment]
Thanks for the hint @cgwalters, and @bgilbert for the clarification.
Closing this...
