### ISSUE TITLE
Not checking `curl` exit code

### ISSUE THREAD

**Issue by jlebon** [coreos/coreos-installer#29]
Just noticed this while reading over the codebase. Should `wait $curl_pid` or something to make sure we error out if `curl` dies halfway.

**Comment by yuqi-zhang** [comment]
Related, note since we're doing a curl -L only, https://github.com/coreos/coreos-installer/blob/master/coreos-installer#L435 will always have a RETCODE of 0

**Comment by arithx** [comment]
@jlebon are you okay with me opening up a different issue for integrity checking and scoping this down to checking the `curl` exit code only?

**Comment by jlebon** [comment]
@arithx Yup, totally fine!

**Comment by arithx** [comment]
Opened up #30 for integrity checking
