### ISSUE TITLE
blockdev: failing with "found multiple devices with label boot" for multi-path installs on s390x

### ISSUE THREAD

**Issue by Prashanth684** [coreos/coreos-installer#370]
On an s390x zVM with FC disk, tried an installation with multipath enabled with the following cmdline:

```
rd.neednet=1 rd.multipath=default console=ttysclp0 coreos.inst.install_dev=sda coreos.live.rootfs_url=http://10.19.14.24:8080/ignition/fedora-coreos-32.20200827.dev.0-live-rootfs.s390x.img coreos.inst.ignition_url=http://bastion.test.example.com:8080/ignition/ignitionv3basic.conf ip=10.19.14.30::10.19.14.254:255.255.255.0:::none nameserver=10.19.14.24 rd.znet=qeth,0.0.0600,0.0.0601,0.0.0602,layer2=1,portno=0 rd.zfcp=0.0.0120,0xC05076CE76800D1C,0x0000000000000000 rd.zfcp=0.0.0130,0xC05076CE76800D70,0x0000000000000000
```

Noticed that the installer fails with the error:

```
coreos-installer-service: Error: found multiple devices on /dev/sda with label "boot"
```

On an lsblk in the emergency shell it looks like there are 2 entries for the boot label:

```
bash-5.0# lsblk --pairs --paths --output NAME,LABEL,FSTYPE,TYPE,MOUNTPOINT,UUID /dev/sda
NAME="/dev/sda" LABEL="" FSTYPE="" TYPE="disk" MOUNTPOINT="" UUID=""
NAME="/dev/sda4" LABEL="root" FSTYPE="xfs" TYPE="part" MOUNTPOINT="" UUID="910678ff-f77e-4a7d-8d53-86f2ac47a823"
NAME="/dev/sda1" LABEL="boot" FSTYPE="ext4" TYPE="part" MOUNTPOINT="" UUID="96d15588-3596-4b3c-adca-a2ff7279ea63"
NAME="/dev/mapper/mpatha" LABEL="" FSTYPE="" TYPE="mpath" MOUNTPOINT="" UUID=""
NAME="/dev/mapper/mpatha1" LABEL="boot" FSTYPE="ext4" TYPE="part" MOUNTPOINT="/boot" UUID="96d15588-3596-4b3c-adca-a2ff7279ea63"
NAME="/dev/mapper/mpatha4" LABEL="root" FSTYPE="xfs" TYPE="part" MOUNTPOINT="/sysroot" UUID="910678ff-f77e-4a7d-8d53-86f2ac47a823"
```

Is this expected for multi-path ? Not sure if this is an s390x hardware specific issue. I have not tried it on x86.

**Comment by hbrueckner** [comment]
@Prashanth684 To install, use the multipath device, mpatha. I wonder about the error multiple devices with label "boot".

A multi-path setup includes different paths to the same disk. Each path is represented by its own sdX device. The multipath daemon creates a logical mpathX devices on top of the sdX belonging to the same disk.

Both problems are generic ones and should also show up on x86 or other arches.

**Comment by nikita-dubrovskii** [comment]
Could you please try `/dev/mapper/mpatha` instead of `sda` ?

**Comment by Prashanth684** [comment]
> Could you please try `/dev/mapper/mpatha` instead of `sda` ?

yes.. `/dev/mapper/mpatha` works. thanks!!
