### ISSUE TITLE
send output of "iso ignition embed" to stdout

### ISSUE THREAD

**Issue by mhrivnak** [coreos/coreos-installer#382]
# Feature Request #
Enable the `coreos-installer iso ignition embed` command to send its output to stdout so that the caller can send that data to its final destination (through whatever means are appropriate to its use case) without needing to write the entire ISO out to the local filesystem.

## Use Case ##
As an example use case, the OpenShift [assisted-service](https://github.com/openshift/assisted-service/) makes RHCOS-based live ISOs available for download over HTTP with embedded ignition that is specific to a user. Rather than a three-step approach that A) makes an entire copy on disk of the ISO, B) streams the resulting file contents via HTTP, then C) deletes that file, it could combine those steps by streaming stdout from the `coreos-installer iso ignition embed` command.

This is particularly valuable when running in a live ISO. In that case, the local filesystem is backed by RAM, so the impact of making a copy of the ISO can be significant. OpenShift's [assisted-service](https://github.com/openshift/assisted-service/) will be delivered to users for [on-premise use as a live ISO](https://github.com/openshift/enhancements/pull/411/files).

## Other Information ##
For syntax, one option is to just support `-` as a valid value for `--output`.

`coreos-installer iso ignition embed -o -`

**Comment by cgwalters** [comment]
While I think we'd consider this somewhat of an implementation detail, today this functionality relies on the https://wiki.osdev.org/ISO_9660#System_Area

So what we should be able to do is copy just the data we need, and then your higher level code can concatenate the two when serving via HTTP.

Something like this:
```
srciso=fedora-coreos-32.20200715.2.2-live.x86_64.iso
destiso=/tmp/test.iso
dd if=${srciso} of=${destiso} bs=1M count=1
truncate -s $(stat -c '%s' ${srciso}) ${destiso}
coreos-installer iso ignition embed -i /path/to/my.ign ${destiso}
```

Then when serving via HTTP, concatenate the first 1M from `${destiso}` with the results of seeking 1M after the start of `${srciso}` or so.

**Comment by cgwalters** [comment]
> For syntax, one option is to just support - as a valid value for --output.
> `coreos-installer iso ignition embed -o -`

Streaming output does seem reasonable and looks like it'd maximize flexibility, offhand it looks like this wouldn't be too hard to implement.

**Comment by bgilbert** [comment]
> coreos-installer iso ignition embed for some reason validates the total ISO size

It's ensuring that the offset/length from the CoreOS header matches reality.

> (OK now that I looked more closely this is going to be very fragile because actually the system area points to the offset of another file we wrote in the ISO which in theory could be anywhere)

Yup.  Your workaround would need to know the offset and length of the embed area, and send the prefix/postfix from the source image and the embed area from the dest image.  That would work, but I don't recommend it.

As of coreos-installer 0.7.0, if the destination filesystem supports copy-on-write file blocks (btrfs or newer XFS), ISO embed will use CoW to reduce I/O.  So you can, at least, arrange to reduce the write traffic for your temporary file.

But I agree we should support `-o -`.  This would be a good issue for someone looking to get started with the codebase.

**Comment by djzager** [comment]
@arithx I tried to track down the Jira issue for this task and was unsuccessful. Still working on this? Mind sharing the Jira link?

**Comment by arithx** [comment]
https://issues.redhat.com/browse/GRPA-2869
