### ISSUE TITLE
install failure: mount: /mount/boot_partition: no filesystem type specified

### ISSUE THREAD

**Issue by yuqi-zhang** [coreos/coreos-installer#39]
In https://github.com/coreos/coreos-installer/commit/520ff67554417a5e38dfe4818fb832e5d1876c18#diff-ce6a85f7960c9e1ec976e71783a56b39 and https://github.com/coreos/coreos-installer/commit/666303d41cb6e06c6e31a239824c9819ca1e26a0#diff-ce6a85f7960c9e1ec976e71783a56b39 we switched to using `/dev/disk/by-uuid/${UUID}` from the previously hardcoded `/dev/disk/by-label/boot`.

On RHCOS this will cause the install to loop on `mount: /mount/boot_partition: no filesystem type specified`, and then failing with `failed mounting boot partition`.

If I try `lsblk /dev/sda --output NAME,LABEL,UUID --pairs` in the emergency shell I get: `NAME="sda" LABEL="" UUID=""` what should be setting those? Is RHCOS missing some `coreos-assembler` patches maybe?

**Comment by ashcrow** [comment]
Hrm, this is a good catch @yuqi-zhang. As part of trying to get RHCOS and FCOS to build from the same tool we will likely need to test ALL changes for both systems.

**Comment by cgwalters** [comment]
> lsblk /dev/sda --output NAME,LABEL,UUID --pairs in the emergency shell I get: NAME="sda" LABEL="" UUID=""

udev should be writing those attributes.  It may be that we have to `udevadm settle` (or better spin and wait for the device to show up; dracut has code like that).

**Comment by dustymabe** [comment]
@yuqi-zhang - after further investigation did you come to any conclusions?

**Comment by yuqi-zhang** [comment]
@dustymabe yes, after some testing I believe https://github.com/coreos/coreos-installer/pull/40 fixed the issue. Sorry for the delay. Closing (will re-open if I find that is not the case).
