### ISSUE TITLE
Delete kargs by regex

### ISSUE THREAD

**Issue by YuviGold** [coreos/coreos-installer#413]
# Feature Request #

## Desired Feature ##
`install --delete-kargs` should support regular expressions.

For example `--delete-kargs 'console=tty[\\w,]+'` to delete all console kargs.

**Comment by bgilbert** [comment]
`--save-partlabel` supports glob patterns, so if we were going to do this, I think globs would be better for consistency.

**Comment by jlebon** [comment]
Hi @YuviGold, we're going to be [removing all the `console` kargs](https://github.com/coreos/fedora-coreos-tracker/issues/567) from the metal images, so the original motivation for this enhancement should go away.

Tentatively closing.
