### ISSUE TITLE
Use bash strict mode

### ISSUE THREAD

**Issue by jlebon** [coreos/coreos-installer#42]
We should use `set -euo pipefail` right at the beginning, aka strict mode: http://redsymbol.net/articles/unofficial-bash-strict-mode/

Otherwise, random errors are just too easy to miss.

**Comment by dustymabe** [comment]
agree - let's just do it and find any issues now

**Comment by bgilbert** [comment]
No longer needed in `master` (#65), probably will not be fixed in `legacy`.
