### ISSUE TITLE
Cannot install onto disk with corrupted GPT

### ISSUE THREAD

**Issue by bgilbert** [coreos/coreos-installer#444]
When installing onto a target disk with a corrupted GPT, coreos-installer will fail with a message similar to:

```
Error: saving partitions from /dev/sda
Caused by: reading partition table
Caused by: corrupted partition entry array CRC32 checksum
```

This failure is intentional when partition saving is enabled, since if we ignored partitions we were supposed to save, data loss would occur.  However, the same logic is invoked when partition saving is not enabled.

As a workaround, the user can manually run `wipefs` on the affected disk.

**Comment by TiloGit** [comment]
@bgilbert  could we get more detail how to work around this.

just got this on RH OCP setup with **Assisted Bare Metal Clusters** setup

error: 
```log
Failed - failed after 3 attempts, last error: failed executing nsenter [-t 1 -m -i -- coreos-installer install --insecure -i /opt/install-dir/master---remvoedUUID---e.ign /dev/sda], 
Error exit status 1, 
LastOutput "Error: saving partitions from /dev/sda 
Caused by: reading partition table Caused by: corrupted partition entry array CRC32 checksum (1703420927 != 2874462854)".
```

**Comment by bgilbert** [comment]
Since you're installing onto `/dev/sda`, you should be able to work around it by invoking `wipefs -a /dev/sda` before running coreos-installer.

**Comment by TiloGit** [comment]
Hi, I tried that but the wipefs didn't report anything to cleanup. 

I got it working by manual writing with `sudo fdisk` GPT table & create partition. (which then was overwritten by the installer)

Let me know if you want me to upload logs of the failed attempts here.

**Comment by bgilbert** [comment]
You are correct.  If the checksums of both the primary and backup GPTs are incorrect, coreos-installer will fail, but wipefs will not recognize and overwrite the GPT signatures.

It should be sufficient to use a partitioning tool to create a new partition table, or alternatively to overwrite the first and last MiB of the disk.
