### ISSUE TITLE
"writing to disk" percentage is off

### ISSUE THREAD

**Issue by dprince** [coreos/coreos-installer#45]
Noticed that the percentage is off a bit today when it is writing the image to disk.

![ignition](https://user-images.githubusercontent.com/140305/59110696-a823a800-890d-11e9-89f9-9af10cee74b2.JPG)

**Comment by dustymabe** [comment]
moved to github.com/coreos/coreos/installer repo

**Comment by dustymabe** [comment]
I have seen this before. In https://github.com/coreos/coreos-installer/pull/16 we removed dialog and added a new percentage reporting mechanism so this should no longer be a problem in future releases.
