### ISSUE TITLE
FR: coreos-installer in LXC without /dev nor /boot

### ISSUE THREAD

**Issue by gattytto** [coreos/coreos-installer#515]
hello, I'm using CoreOS in LXC and used [this web post](https://www.eclipse.org/che/docs/che-7/installation-guide/installing-che-on-minikube/#using-minikube-with-lxc_che)  to set up cri-o inside lxc containers.

previously I used LXC ubuntu images for spinning up a minikube single node cluster and then a baremetal kubernetes cluster using kubeadm, now I want to do the same but using openshift, coreos and coreos-installer. 

can I please get some help? relevant info about the setup is [here](https://github.com/lxc/lxc/issues/3768#issue-849910874) and [here](https://github.com/lxc/distrobuilder/issues/254#issuecomment-810492276)

**Comment by bgilbert** [comment]
Do I understand correctly that you're trying to run Fedora CoreOS in a container?  FCOS is intended as a host for running containers, not as the OS inside a container.  Fedora CoreOS ships as a disk image that needs to be installed to a block device, which is why `coreos-installer` requires access to `/dev`.

**Comment by gattytto** [comment]
thank you for your answer @bgilbert I'll add some context: I'm using LXC containers as baremetal kubernetes nodes, and after passing the coreos raw rootdir to a lxc image I was able to run coreos inside lxc and even cri-o to run some pods. 

I'll close this issue since my intention is to continue the cluster bootstrapping process in lxc using openshift-installer and it is not related to coreos-installer.
