### ISSUE TITLE
Don't require specifying image URL

### ISSUE THREAD

**Issue by bgilbert** [coreos/coreos-installer#53]
For Fedora CoreOS, it should be sufficient to specify the release stream, defaulting to `stable`.  coreos-installer should obtain the correct URL from stream metadata.

**Comment by dustymabe** [comment]
@bgilbert do you want to add this to a board ?

**Comment by Limero** [comment]
This would be very useful. Having to type a whole URL on a bare metal install takes way too long.

**Comment by bgilbert** [comment]
Fixed in #65.

**Comment by Limero** [comment]
What is the `coreos-installer` syntax for doing an install with the latest `testing` stream after this fix? The `-b` flag seems to still require a whole URL and I can't find any updated documentation.

**Comment by bgilbert** [comment]
Yeah, the README still needs an update.  You'll want something like:

```sh
coreos-installer install /dev/sda -s testing
```

Note that you'll currently need to get coreos-installer with `cargo` or run the [container image](https://quay.io/repository/coreos/coreos-installer), since we're not shipping the rewrite in Fedora CoreOS yet.
