### ISSUE TITLE
macos 10.15 build error "error[E0425]: cannot find function `syncfs` in crate `libc`"

### ISSUE THREAD

**Issue by eriksjolund** [coreos/coreos-installer#569]
# Bug #
Building on macos 10.15 fails.

Trying to build coreos-installer on macos 10.15 in a GitHub Actions runner with this workflow

https://github.com/eriksjolund/coreos-installer/blob/c79d4b61010997380638590a6c7fc1322977f551/.github/workflows/rust.yml

(I'm not quite sure if should be possible to build and run coreos-installer on macos)

## Host Operating System Version ##

GitHub Actions runner: _macos-latest_ (10.15)
Such a runner has this software preinstalled:
https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md

## coreos-installer Version ##

I forked the coreos-repo into 
https://github.com/eriksjolund/coreos-installer/
and modified .github/workflows/rust.yml
so that it would build on macos-runner.
The macos build was triggered from this git commit:

https://github.com/eriksjolund/coreos-installer/commit/c79d4b61010997380638590a6c7fc1322977f551

## Expected Behavior ##

Successful build

## Actual Behavior ##

See
https://github.com/eriksjolund/coreos-installer/runs/2979067290?check_suite_focus=true

Copy-paste of some of the output:
```
   Compiling cpio v0.2.0
   Compiling tokio v1.0.1
   Compiling indexmap v1.3.2
   Compiling crossbeam-utils v0.8.1
   Compiling memoffset v0.6.4
   Compiling tracing-core v0.1.17
   Compiling futures-channel v0.3.4
   Compiling openssl-sys v0.9.64
   Compiling lzma-sys v0.1.15
   Compiling unicode-bidi v0.3.4
   Compiling http v0.2.1
   Compiling unicode-normalization v0.1.12
   Compiling crc v1.8.1
   Compiling form_urlencoded v1.0.0
   Compiling miniz_oxide v0.4.0
   Compiling foreign-types v0.3.2
   Compiling textwrap v0.11.0
   Compiling byte-unit v4.0.12
   Compiling walkdir v2.3.2
   Compiling tracing v0.1.22
   Compiling idna v0.2.0
   Compiling http-body v0.4.0
   Compiling want v0.3.0
   Compiling quote v1.0.3
   Compiling futures-util v0.3.4
   Compiling aho-corasick v0.7.18
   Compiling mio v0.7.7
   Compiling num_cpus v1.12.0
   Compiling core-foundation v0.9.1
   Compiling security-framework-sys v2.1.1
   Compiling socket2 v0.3.19
   Compiling atty v0.2.14
   Compiling openat v0.1.20
   Compiling flate2 v1.0.20
   Compiling url v2.2.2
   Compiling nix v0.21.0
   Compiling crossbeam-channel v0.5.0
   Compiling regex v1.5.4
   Compiling rand_core v0.6.1
   Compiling uuid v0.8.2
   Compiling security-framework v2.1.2
   Compiling clap v2.33.3
   Compiling xz2 v0.1.6
   Compiling pipe v0.4.0
   Compiling rand_chacha v0.3.0
   Compiling tokio-stream v0.1.1
   Compiling pin-project-internal v0.4.8
   Compiling pin-project-internal v1.0.3
   Compiling thiserror-impl v1.0.24
   Compiling rand v0.8.4
   Compiling tokio-util v0.6.0
   Compiling pin-project v0.4.8
   Compiling pin-project v1.0.3
   Compiling thiserror v1.0.24
   Compiling tempfile v3.2.0
   Compiling openat-ext v0.2.1
error[E0425]: cannot find function `syncfs` in crate `libc`
   --> /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/openat-ext-0.2.1/src/lib.rs:343:34
    |
343 |         let ret = unsafe { libc::syncfs(dirfd.as_raw_fd()) };
    |                                  ^^^^^^ help: a function with a similar name exists: `sync`
    | 
   ::: /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.97/src/unix/bsd/mod.rs:726:5
    |
726 |     pub fn sync();
    |     -------------- similarly named function `sync` defined here
```

**Comment by bgilbert** [comment]
coreos-installer isn't expected to build or run on macOS.  What's the use case you have in mind?

**Comment by eriksjolund** [comment]
The use case would be running coreos-installer in a GitHub Action
https://discussion.fedoraproject.org/t/demo-boot-fedora-coreos-in-a-github-action-from-a-butane-config/31556/2

The GitHub-hosted runner _macos-10.15_ provides VirtualBox to run VM:s (hardware accelerated).
Unfortunately the same runner does not have _Docker_ or _Podman_ installed.
A workaround could be to install one of them and run _coreos-installer_ in a container.

Another possibility could be to have another GitHub Action job running on the GitHub-hosted runner _ubuntu-20.04_, that could
run _coreos-installer_ and upload the result to an GitHub Action artifact. Such an artifact could then
be downloaded from a _macos-10.15_  GitHub-hosted runner.

**Comment by bgilbert** [comment]
Ideally we'd have VirtualBox images that supported specifying an Ignition config directly, so coreos-installer wasn't required at all, but see https://github.com/coreos/ignition/issues/629.

For now, either of those workarounds could work.  `coreos-installer install --ignition-{file,url}` requires the host kernel to understand the ext4 filesystem, so the `install` subcommand can't easily be made to work on a Mac.
