### ISSUE TITLE
core os installer should wipe off the existing partitions on bare metal in order for new ignition file to be effective

### ISSUE THREAD

**Issue by tpatel84** [coreos/coreos-installer#63]
Hi Core Os Team,

I experience this issue when i was trying to install core os on bare metal with following steps : 

1) Generate ignition files using openshift-installer
2) Copy these ignition files to HTTP server. 
3) Also , copy one of these core os file to http server as well : a) *.metal-bbios.raw.gz or b) *.metal-uefi.raw.gz.
4) Boot the bootstrap server using core os iso image.
5) During install hit TAB key and provide a) install disk b) boot strap ignition_url c) rhcos image url (from step #3)
6) Install core os on remaining servers with appropriate ignition files i.e. For master master.ign and for worker, worker.ign.
7) If user fail to configure the cluster within 24 hour, They have to regenrate the ignition files since ignition files are good for 24 hr.
8) Follow step 1 to 3 again.
9) When user try to install same or new core os build with NEW ignition files from step #8, It won't be effective since ignition file will be effective on first boot or fresh disk with no partition on it.

Looking at core os installer script, It does wipefs and dd but it doesn't delete the partition. 

Temp Workaround : Boot server from rescue mode and use fdisk to delete the partition (wipefs id not available command in rescue mode)

Following is the core os slack channel conversation link : 
Link : https://coreos.slack.com/archives/C999USB0D/p1568831140099000

**Comment by bgilbert** [comment]
During the second install, dd overwrites all of the old partitions, so the behavior you're describing shouldn't be possible.  Are you certain that you pointed the installer to the new Ignition files during the second install?

**Comment by bgilbert** [comment]
This seems likely to be a misunderstanding, so I'll close.  Please feel free to reopen if you have more details or are still seeing this issue.

**Comment by tapatel** [comment]
Hi Gilbert, 

Sorry was in training whole and didn't get a chance to respond in time. 

Yes, When i try to install core os 2nd time using new ignition file uploaded to http server, It didn't applied new ignition file and hence openshift installer was failing for same reason. 

Regards,
Tarun
