### ISSUE TITLE
Unable to configure bonding interface through cmdline args

### ISSUE THREAD

**Issue by rsevilla87** [coreos/coreos-installer#64]
Hi, 
I'm not sure if this is the right repo to report this issue, because the it's related with a script that is not here, however I didn't find a better place
Configuring a bond interface using the cmdline arguments doesn't work as expected. After adding the arguments:
```
ip=172.26.100.14::172.26.100.254:255.255.255.0::bond0:none:172.26.100.2 bond=bond0:ens3,ens7:mode=1
```
RHCOS installer starts normally, downloads the related ignition file, write the disk image on the given block device, but after rebooting it hangs during the initramfs stage.
I've seen that the following service doesn't work fine.

```
:/# systemctl status coreos-teardown-initramfs-network.service -l 
● coreos-teardown-initramfs-network.service - Tear down initramfs networking
   Loaded: loaded (/usr/lib/systemd/system/coreos-teardown-initramfs-network.se>
   Active: failed (Result: exit-code) since Wed 2019-10-02 20:28:10 UTC; 12min >
  Process: 984 ExecStop=/usr/sbin/coreos-teardown-initramfs-network (code=exite>

Oct 02 20:28:09 localhost systemd[1]: Started Tear down initramfs networking.
Oct 02 20:28:09 localhost systemd[1]: Stopping Tear down initramfs networking...
Oct 02 20:28:10 localhost coreos-teardown-initramfs-network[984]: device "bonding_masters"
Oct 02 20:28:10 localhost systemd[1]: coreos-teardown-initramfs-network.service: Control process exited, code=exited
Oct 02 20:28:10 localhost systemd[1]: coreos-teardown-initramfs-network.service: : Failed with result 'exit-code'.
Oct 02 20:28:10 localhost systemd[1]: Stopped Tear down initramfs networking.
Oct 02 20:28:10 localhost systemd[1]: coreos-teardown-initramfs-network.service: Triggering OnFailure= dependencies
```

Taking a look to the coreos-teardown-initramfs-network script:
```shell
:/# cat /usr/sbin/coreos-teardown-initramfs-network 
#!/bin/bash
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

set -euo pipefail

# Clean up the interfaces set up in the initramfs
# This mimics the behaviour of dracut's ifdown() in net-lib.sh
if ! [ -z "$(ls /sys/class/net)" ]; then
    for f in /sys/class/net/*; do
        interface=$(basename "$f")
        ip link set $interface down
        ip addr flush dev $interface
        rm -f -- /tmp/net.$interface.did-setup
    done
fi
```

I've noticed that this script is trying to bring up the device *bonding_masters*, which is not a real interface (In fact is a way to create bond interfaces through sysfs), I think we should filter this name to make this work as expected, but as I said previously, I didn't find this code on github :(

Thanks in advance,

**Comment by yuqi-zhang** [comment]
Hi, thanks for the report!

https://github.com/coreos/ignition-dracut/blob/spec2x/dracut/30ignition/coreos-teardown-initramfs-network.sh

It was initially intended as a teardown script for basic networking interfaces (very basic) and definitely needs improvement. In fact I'm not 100% sure if its necessary anymore now that we have karg persisting. Definitely something we should look into. cc @miabbott

**Comment by rsevilla87** [comment]
Fixed at https://github.com/coreos/ignition-dracut/pull/123
