### ISSUE TITLE
Consider branching coreos-installer repo for Rust rewrite

### ISSUE THREAD

**Issue by bgilbert** [coreos/coreos-installer#66]
The plan is to drop the Dracut module in favor of a systemd unit running in the real root.  While RHCOS is still using the old installer and Dracut module, it'd be possible to carry both codebases in the same repo, but it seems confusing.  Should we maintain the old installer in a legacy branch instead?

**Comment by miabbott** [comment]
:+1: to branching

**Comment by bgilbert** [comment]
Discussed OOB and there was a general consensus for branching.

**Comment by bgilbert** [comment]
Created `legacy` branch for the shell script version.
