### ISSUE TITLE
tmpfs too small when image is behind an HTTP redirect

### ISSUE THREAD

**Issue by keithy** [coreos/coreos-installer#69]
Attempts to use coreos-installer fail to download the raw image because the /mnt/dl tmpfs file system is set to 50Mb in size, while the image is 500+ Perhaps I have the wrong image... hmm.

**Comment by bgilbert** [comment]
This now only affects the `legacy` branch.

**Comment by bgilbert** [comment]
The legacy branch of coreos-installer is no longer supported or maintained, so I'll close this out.  Thanks for reporting.
