### ISSUE TITLE
Show download URL with a flag

### ISSUE THREAD

**Issue by carlocorradini** [coreos/coreos-installer#699]
# Feature Request #
I'm trying to automate the procedure of building a custom ISO (Download -> Compile .bu into .ign -> Embed) and I want to obtain the filename of the downloaded file using the download command.

The overall procedure is done calling multiple times podman and the respective coreos-installer:release image. I mount the current directory and do all the operations. Obtaining the filename from an URL is super easy: ```${URL##*/}```.
Please see "Other Information" section.

I think that having an option in ```coreos-installer:release download``` to show the "composed" download URL could be super useful (not only for me): *You specify all the related information (e.g stream, architecture, format, ...) and passing a flag (e.g --show) you obtain the download URL.*
I don't know if it's good to also download the file or only show the URL and exit, please help :) Thanks

## Desired Feature ##
Obtain the "composed" URL from download command (and exit?) with a specific flag (e.g ```--show```).
Here is an example:
```coreos-installer download --format iso --stream stable --architecture x86_64 --show```

## Other Information ##
I'm not a shell scripting expert but more or less this is what I'm trying to achieve and obtaining the filename as I do is not the best:
```sh
#!/usr/bin/env bash

set -o errexit
set -o nounset

readonly __DIRNAME="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# --- CONFIG ---
readonly DEBUG=false
readonly BUILD_DIR="${__DIRNAME}/build"
readonly DEPS_DIR="${BUILD_DIR}/deps"
# Container Engine
readonly CE=docker
readonly CE_WORKDIR="/workdir"
# CoreOS
readonly COREOS_DOWNLOAD_STREAM="stable"        # stable | testing | next
readonly COREOS_DOWNLOAD_ARCHITECTURE="x86_64"  # x86_64 | aarch64
readonly COREOS_BUTANE_FILE="autoinstall.bu"
# ---

# --- INIT ---
# Enable debug
if [ "${DEBUG}" = true ]; then set -o xtrace; fi
# Remove build directory
if [ -d "${BUILD_DIR}" ]; then rm -r ${BUILD_DIR}; fi
# Make build directory tree
mkdir ${BUILD_DIR} ${DEPS_DIR}
# ---

main() {
    # Download CoreOS iso
    ${CE} run --rm -v "${__DIRNAME}:${CE_WORKDIR}" -w "${CE_WORKDIR}" quay.io/coreos/coreos-installer:release download --format iso --stream "${COREOS_DOWNLOAD_STREAM}" --architecture "${COREOS_DOWNLOAD_ARCHITECTURE}" --directory "${CE_WORKDIR}${DEPS_DIR#$__DIRNAME}"
    
    # Produce ignition file
    local coreos_ignition_filename="${COREOS_BUTANE_FILE%.*}.ign"
    ${CE} run --rm -v "${__DIRNAME}:${CE_WORKDIR}" -w "${CE_WORKDIR}" quay.io/coreos/butane:release --pretty --strict "${CE_WORKDIR}/${COREOS_BUTANE_FILE}" > "${DEPS_DIR}/${coreos_ignition_filename}"
    
    # Embed ignition file into CoreOS iso
    local coreos_iso_filename="";
    for iso in ${DEPS_DIR}/*; do
        if [ "${iso: -4}" == ".iso" ]; then
            coreos_iso_filename="${iso##*/}"
            break
        fi
    done
    # TODO Check if exists
    ${CE} run --rm -v "${__DIRNAME}:${CE_WORKDIR}" -w "${CE_WORKDIR}" quay.io/coreos/coreos-installer:release iso ignition embed --force --ignition-file "${CE_WORKDIR}/${DEPS_DIR#$__DIRNAME}/${coreos_ignition_filename}" --output "${CE_WORKDIR}${BUILD_DIR#$__DIRNAME}/${coreos_iso_filename}" "${CE_WORKDIR}${DEPS_DIR#$__DIRNAME}/${coreos_iso_filename}"
    
    return 0
}

main
```

**Comment by bgilbert** [comment]
> I'm trying to automate the procedure of building a custom ISO (Download -> Compile .bu into .ign -> Embed) and I want to obtain the filename of the downloaded file using the download command.

We already print this on stdout, so you should be able to just capture the output of the download command:

```
$ path=$(podman run --pull=always --security-opt label=disable -v $(pwd):/data quay.io/coreos/coreos-installer:release download --format iso -C /data)
Trying to pull quay.io/coreos/coreos-installer:release...
Getting image source signatures
Copying blob 2469a793457d skipped: already exists  
Copying blob b8e2a57e341e skipped: already exists  
Copying blob 0c2ae48d4544 skipped: already exists  
Copying blob a3ed95caeb02 done  
Writing manifest to image destination
Storing signatures
Downloading Fedora CoreOS stable x86_64 metal image (iso) and signature
Read disk 11.2 MiB/740.0 MiB (1%)
[...]
Read disk 740.0 MiB/740.0 MiB (100%)
gpg: Signature made Thu Nov 18 01:30:11 2021 UTC
gpg:                using RSA key 787EA6AE1147EEE56C40B30CDB4639719867C58F
gpg: Good signature from "Fedora (35) <fedora-35-primary@fedoraproject.org>" [ultimate]
$ echo $path
/data/fedora-coreos-35.20211029.3.0-live.x86_64.iso
```

The path is printed from the container's perspective, but you can use `basename "${path}"` to get the filename.

**Comment by carlocorradini** [comment]
Thanks @bgilbert ! 🤯
