### ISSUE TITLE
coreos-installer-growfs[747]: mount: /sysroot: /dev/vda4 already mounted on /sysroot/sysroot.

### ISSUE THREAD

**Issue by Rtoax** [coreos/coreos-installer#701]
# Bug #

```
-- Logs begin at Thu 2021-12-02 13:04:45 UTC, end at Thu 2021-12-02 13:04:53 UTC. --
Dec 02 13:04:47 systemd[1]: Starting Grow root filesystem...
Dec 02 13:04:52 coreos-installer-growfs[747]: xfs
Dec 02 13:04:52 coreos-installer-growfs[747]: mount: /sysroot: /dev/vda4 already mounted on /sysroot/sysroot.
Dec 02 13:04:52 systemd[1]: coreos-installer-growfs.service: Main process exited, code=exited, status=32/n/a
Dec 02 13:04:52 systemd[1]: coreos-installer-growfs.service: Failed with result 'exit-code'.
Dec 02 13:04:52 systemd[1]: Failed to start Grow root filesystem.
-- Logs begin at Thu 2021-12-02 13:04:45 UTC, end at Thu 2021-12-02 13:04:53 UTC. --
Dec 02 13:04:52 systemd[1]: Starting Cleaning Up and Shutting Down Daemons...
Dec 02 13:04:53 systemd[1]: initrd-cleanup.service: Main process exited, code=exited, status=4/NOPERMISSION
Dec 02 13:04:53 systemctl[1003]: Failed to start initrd-switch-root.target: Transaction is destructive.
Dec 02 13:04:53 systemctl[1003]: See system logs and 'systemctl status initrd-switch-root.target' for details.
Dec 02 13:04:53 systemd[1]: initrd-cleanup.service: Failed with result 'exit-code'.
Dec 02 13:04:53 systemd[1]: Failed to start Cleaning Up and Shutting Down Daemons.
Dec 02 13:04:53 systemd[1]: initrd-cleanup.service: Triggering OnFailure= dependencies.
qemu-system-x86_64: terminating on signal 1 from pid 0 (/usr/bin/dumb-init)   
qemu-system-x86_64: tpm-emulator: Could not cleanly shutdown the TPM: Invalid argument
```

## Host Operating System Version ##

CentOS8

## Target Operating System Version ##

FedoraCoreOS 35

## coreos-installer Version ##

0.11.0

## Expected Behavior ##

see LOGs above

## Actual Behavior ##

see LOGs above

## Reproduction Steps ##

  1. ...
  2. ...

**Comment by lucab** [comment]
Thanks for the report, but there too many details missing for the context around this.
Which FCOS image and version is this? And how are you running it? And how is coreos-installer being used?

**Comment by jlebon** [comment]
`coreos-installer-growfs` is from `coreos-installer-dracut`, which we don't ship in FCOS. Are you trying to install Fedora IoT or RHEL Edge?

**Comment by dustymabe** [comment]
Hey @Rtoax - We periodicially go through and close issues that are lacking enough information for us to take any action. For your various issues/PRs you have open please try to make sure you answer any open questions or requests for more information that exist.

When you open new issues or PRs in the future it will help to add as much information as you can to make sure we can glean all of the context on why an issue is an issue or why a change is needed.

**Comment by bgilbert** [comment]
Closing due to lack of response.  If you can provide the missing information, please feel free to reopen this issue.
