### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by rootqu** [coreos/coreos-installer#76]
Hello CoreOS Team,

I wanted to install CoreOS today however on line 492 given error. Why would that be?

log:

gpg: Good signature from "CoreOS Buildbot (Offical Builds) <buildbot@coreos.com>" [ultimate]
./coreos-install: line 492:  4920 Segmentation fault      udevadm settle

Help me please,
Thanks

**Comment by arithx** [comment]
Hi, `coreos-install` (the installer for Container Linux) is different from `coreos-installer` (the installer used by FCOS/RHCOS).

If you're having issues with using it to install Container Linux please open an issue in https://github.com/coreos/bugs
