### ISSUE TITLE
Partition saving doesn't notice MBR partitions

### ISSUE THREAD

**Issue by bgilbert** [coreos/coreos-installer#816]
# Bug #

## Host Operating System Version ##

Any

## Target Operating System Version ##

Any

## coreos-installer Version ##

All releases through 0.13.1

## Expected Behavior ##

`coreos-installer install --save-partindex` correctly saves partitions on disks that have an MBR partition table and no GPT.

## Actual Behavior ##

`coreos-installer install --save-partindex` clobbers such partitions.

## Reproduction Steps ##

1. Use `fdisk` to create a partition on a blank target disk
2. Install to the disk, passing `--save-partindex` to save the partition

## Other Information ##

`--save-partlabel` isn't affected because MBR doesn't support partition labels.

We could support this via mbrman.  We'd need to detect and ignore protective MBRs, and to fail if the MBR otherwise doesn't match a valid GPT.

**Comment by prestist** [comment]
In speaking with @bgilbert we are going to be taking this issue with a 2 pronged approach

1. Mitigation reduce risk of data loss from unexpected clobbering of saved partitions. 
2. Migrate MBR saved partitions to GPT format so the installer can effectively save them.
