### ISSUE TITLE
Give clearer error message when ISO file is not complete

### ISSUE THREAD

**Issue by sshnaidm** [coreos/coreos-installer#869]
# Bug #

Misleading error message when using not fully downloaded rhcos ISO image.
I haven't download the image fully, it's only 512M size. When I'm running `coreos-installer iso kargs modify -a "ip=dhcp"` command on this ISO, I get the message:
```
Error: reading kargs embed area

Caused by:
    0: reading 1132 bytes at 1082311624
    1: failed to fill whole buffer
```

## Host Operating System Version ##
RHEL 8.2
## coreos-installer Version ##
0.14, 0.11
## Expected Behavior ##
Message about `Error: reading kargs embed area`

## Actual Behavior ##

Probably would be better to detect that the image is wrong and can't be modified.

## Reproduction Steps ##
Start download ISO of RHCOS, stop it in the middle and run the command:
`$ coreos-installer iso kargs modify -a "ip=dhcp" rhcos-411.85.202205101201-0-live.x86_64.iso`

**Comment by jlebon** [comment]
I think one of the base issues is that `seek` doesn't error out by default if seeking past the end of the file. There's `SEEK_DATA` which would (and then we could catch `ENXIO` and give a nicer error), but we'd need to look beyond `std::io` for it (it also doesn't seem supported on every filesystem, though all the popular ones at least). We could also wrap seeks intended for subsequent reads with a method that also does a follow-up `read` of one byte.

**Comment by jlebon** [comment]
Hmm, actually another simpler check we can do upfront is to just get the offset of the last file in the ISO and verify that `file offset + file length <= ISO length`.

**Comment by travier** [comment]
Yes, I was thinking we could do a basic "is this file large enough?" check to quickly root out such issues.

**Comment by jlebon** [comment]
Related: https://github.com/coreos/coreos-installer/issues/644

If `coreos-installer download` were supported for OCP, we'd correctly verify checksums.

**Comment by travier** [comment]
@bgilbert is this fixed by https://github.com/coreos/coreos-installer/pull/908?

**Comment by bgilbert** [comment]
Yes, it is.
