### ISSUE TITLE
 Where can I find the example of identity.cfg  fedora-coreos-30.20190801.0-metal.raw.xz

### ISSUE THREAD

**Issue by jackadam1981** [coreos/coreos-installer#89]
/usr/libexec/coreos-installer -d sdd -i https://example.com/ignition.cfg -b https://example.com/fedora-coreos-30.20190801.0-metal.raw.xz

**Comment by lucab** [comment]
@jackadam1981 the "getting started" doc-page has a short section on how to generate them from human-friendly configuration https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/#_generating_ignition_configs.

All the details about Ignition are covered by its documentation: https://github.com/coreos/ignition/tree/master/doc
