### ISSUE TITLE
Add option to have iso customize install on first available drive

### ISSUE THREAD

**Issue by loganmc10** [coreos/coreos-installer#892]
# Feature Request #
Right now, ```iso customize``` requires you to specify ```--dest-device``` in order to have it automatically install without any user intervention.

This makes it hard to distribute an ISO to users, you don't know if their drive is /dev/sda, /dev/vda, or maybe an nvme drive.

It would be nice to have an option to just wipe all available drives and install, somewhat similar to how the OpenShift Assisted Installer does it.

**Comment by bgilbert** [comment]
Both Ignition and coreos-installer intentionally require the user to specify which disks should be used as OS disks or data disks.  The "first available drive" isn't a well-defined concept: for example, `/dev/sda` may point to a different disk on each boot, depending on the order that the kernel happens to discover each drive.  And the available disks may have different sizes and speeds, etc., so autoselection may not make sense.

Also, CoreOS systems are generally intended to be reprovisioned as needed.  In particular, outside of OpenShift or OKD, the recommended way to apply configuration changes is to reprovision the machine with an updated Ignition config.  When doing so, it's important that each disk retains the same role (OS disk vs. data disk 1 vs. data disk 2, etc.) so any existing persistent data is preserved.  As a result, users need to exercise control over disk selection to match their needs.

If desired, you can provide a script to select an installation disk according to your own rules.  Use `coreos-installer iso customize` or `coreos-installer pxe customize` to specify a `--pre-install` [hook](https://coreos.github.io/coreos-installer/customizing-install/#customize-options), which can then write the install device into a [config file](https://coreos.github.io/coreos-installer/customizing-install/#config-file-format) in `/etc/coreos/installer.d`.

**Comment by loganmc10** [comment]
I just want to point out that this is something that the Assisted Installer does for OpenShift, you don't need to tell it which disk to install on. So it's not unheard of or impossible.

**Comment by bgilbert** [comment]
The Assisted Installer is a higher-level tool, designed (for good reason) with a different set of priorities and tradeoffs. Much of what I described could be mostly addressed with enough heuristics, but as a general principle, we try to build tools that don't guess.  For the foreseeable future we'll be leaving these sorts of affordances to higher-level tools.
