### ISSUE TITLE
I would like to know how to use coreos-installer install --append-karg to add a static IP and nameserver, can you give an example?

### ISSUE THREAD

**Issue by fengzhigu2000** [coreos/coreos-installer#933]
I use fedora-coreos-35.iso

**Comment by bgilbert** [comment]
See the _Network_ section of [`dracut.cmdline(7)`](https://man7.org/linux/man-pages/man7/dracut.cmdline.7.html).

Also note that Fedora CoreOS 35 is no longer supported.  We recommend always using the latest version of Fedora CoreOS.
