### ISSUE TITLE
USB path should be supported for coreos.inst.image_url

### ISSUE THREAD

**Issue by imranrazakhan** [coreos/coreos-installer#97]
# Feature Request #
Like Anaconda installation we can provide kickstart file from second USB, same option should be available in FCOS to provide raw image from USB.

```
label linux
  menu label ^Install CentOS 7
  kernel vmlinuz
  append initrd=initrd.img inst.stage2=hd:LABEL=CentOSISO inst.ks=hd:LABEL=MYKS:ks.cfg quiet
```
Above is part of isolinux.cfg and we are using two USB one for iso and one for KickStart, Similar way it should allow to specify USB path for **coreos.inst.image_url**

**Comment by lucab** [comment]
We have reworked the installer to work as a normal (or containerized) binary. This should provide enough flexibility to do what you want, without using kernel arguments at all.

Please check the current README for the standalone binary/container mode.

**Comment by bgilbert** [comment]
I'll close.  Please reopen if you feel your issue has not been addressed.
